### ISSUE TITLE
Not working on ep-1320

### ISSUE THREAD

**Issue by Comradevergreen** [garrettjwilke/ep_133_sample_tool#4]
When I open the app it just shows this screen
<img width="1297" alt="Screenshot 2024-10-27 at 11 43 44" src="https://github.com/user-attachments/assets/813fb1b7-ccae-4422-8977-b0adb777a33a">
And in the console there's error thrown multiple times

```
index2.js:9674 Uncaught ReferenceError: Enable133 is not defined
    at parseMidiIdentityResponse (index2.js:9674:13)
    at SysexClient.handleMidiMessages (index2.js:9617:19)
    at inputs.has.s.onmidimessage (index2.js:9356:30)
```

I tried initializing Enabled133 with false and it worked. Seems like in index2.js:9674 it should be Fake133. I tried fixing it locally and it worked

**Comment by garrettjwilke** [comment]
ahh...thank you for testing this...i do not have a 1320, so i had to guess how that would work...
thank you for the pull request, i apologize for being so late on this :)

**Comment by tev** [comment]
Can you release a build with this fix? I'm having that issue as well.
